export const REDIS_CLIENT_TOKEN_SUFFIX = "Redis";
export const REDIS_CLIENT_NAME_TOKEN = "REDIS_CLIENT_NAME";
export const REDIS_ADAPTER_CONSTRUCTOR_TOKEN = "REDIS_ADAPTER_CONSTRUCTOR";
export const REDIS_EMITTER_TOKEN = "REDIS_EMITTER";
